name: Create Pull Request
on:
  push:
    branches:
      - 'submit/*'

jobs:
  pr:
    name: Create Pull Request
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.VBOX_DEPLOY_TOKEN }}
          pr_label: 'bot'
