name: Create Pull Request
on:
  push:
    branches:
      - 'submit/*'

jobs:
  pr:
    name: Create Pull Request
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.VBOX_DEPLOY_TOKEN }}
          pr_label: 'bot'
          # pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          # pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          # pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
